### ISSUE TITLE
how to run sample faceDetection?

### ISSUE THREAD

**Issue by wiliamc** [RiweiChen/DeepFace#18]
I builded the caffe in the DeepFace/resource/caffe-local 
1.When i build the caffe it shows the following error.

> src/caffe/layers/window_data_layer.cpp:25:11: error: ‘const int CV_LOAD_IMAGE_COLOR’ redeclared as different kind of symbol
>  const int CV_LOAD_IMAGE_COLOR = cv::IMREAD_COLOR;

So i commented the above line in src/caffe/layers/window_data_layer.cp
 Caffe is builded succesfully

2.Then changed the caffe path in the Facedetection/baseline/evaluate_48.py and run 
        python evaluate_48.py
 It shows the error
File "evaluate_48.py", line 13, in <module>

> ```
> import caffe
> ```
> 
>   File "/home/hubino/Documents/DeepFace/resource/caffe-local/python/caffe/**init**.py", line 1, in <module>
>     from .pycaffe import Net, SGDSolver
>   File "/home/hubino/Documents/DeepFace/resource/caffe-local/python/caffe/pycaffe.py", line 10, in <module>
>     from ._caffe import Net, SGDSolver
> ImportError: libcudart.so.6.5: cannot open shared object file: No such file or directory

3.Then i deleted the puthon caffe library and builded the python caffe library(_caffe.so),since i am using cuda7.5.

4.Then build the evaluate_48.py,it shows error

> Traceback (most recent call last):
>   File "evaluate_48.py", line 17, in <module>
>     caffe.set_device(0)
> AttributeError: 'module' object has no attribute 'set_device'

**1.How to solve this error?
2.Can you please update the readme with instruction,which will be useful to build the samples**

I also tried to run the script train.sh in the try1_4 folder
The caffe is loaded,but it shows error

> I0810 20:23:37.807682 11183 solver.cpp:67] Creating training net from net file: train_val.prototxt
> [libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 3:7: Message type "caffe.NetParameter" has no field named "layer".

How to solve it?

**Comment by chenriwei** [comment]
hi, @cibin91 ,the problem is that " caffe-local " branch is based on the very old version of caffe (time of 2014 or so), the big different is that, in the old Version, the layer define is like this:

# old style

layers {
  name: "pool1"
  type: POOLING
  bottom: "conv1"

# new style

layer {
  name: "pool1"
  type:  "Pooling"
  bottom: "norm1"

so, how to solve this:

Way 1: using the update version of caffe (recommend)
Way 2: use Caffe tools to upgrade the model and prototxt file ref([](https://github.com/BVLC/caffe/blob/master/tools/upgrade_net_proto_binary.cpp).

Hope it can help you.
